export const receitas = {
    entrada: [
      {
        nome: "Cebola enrolada no bacon",
        ingredientes: [
          "Cebola",
          "Pimenta",
          "Sal",
          "Limão",
          "Bacon em tiras",
          "Palitos de madeira",
        ],
        modo_preparo: [
          "Corte a cebola em rodelas de um dedo de espessura e remova o miolo",
          "Em uma tigela, tempere as cebolas com pimenta, sal e limão. Deixe descansar por 15 minutos",
          "Remova as cebolas da tigela e reserve o tempero",
          "Enrole uma rodela de cebola com bacon até envolvê-la inteira",
          "Espete palitos de madeira para segurar o bacon e coloque-a no tempero novamente",
          "Repita o processo até acabarem as cebolas e o bacon",
          "Leve para a churrasqueira e espere dourar",
        ],
        id_video: "giFLUZ8691I",
        tempo: "20 minutos", 
        porcao: "6",
        por: "Todo sobre el asado",
        img: "cebola",
        tipo: "entrada",
      },
      {
        nome: "Aperitivo de batatinha",
        ingredientes: [
          "2 kg de batatinha",
          "Sal",
          "Azeite",
          "1 colher de chá de pimenta calabresa",
          "1 colher de sopa de orégano",
          "1 colher de café de pimenta-do-reino",
          "1 colher de chá de cúrcuma",
          "2 colheres de sopa de salsinha",
          "4 dentes de alho",
        ],
        modo_preparo: [
          "Lave as batatas e transfira-as para uma panela com água e sal. Cozinhe até que elas fiquem macias",
          "Escorra a água e reserve as batatas",
          "Em uma frigideira, aqueça o azeite. Adicione alho, pimenta calabresa, orégano, pimenta-do-reino, cúrcuma, salsinha e sal. Refogue",
          "Adicione as batatas à panela e misture muito bem.",
        ],
        id_video: "l_rn6AB0nPk",
        tempo: "45 minutos",
        porcao: "7",
        por: "Fernando Couto",
        img: "batatinha",
        tipo: "entrada",
      },
      {
        nome: "Compota de tomate-cereja",
        ingredientes: [
          "500 g de tomate-cereja",
          "2 colheres de sopa de açúcar cristal",
          "Pimenta-do-reino",
          "Sal",
          "Azeite",
          "1 ou 2 colheres de sopa de azeite balsâmico",
        ],
        modo_preparo: [
          "Lave e corte os tomates. Então, espalhe-os sobre uma forma",
          "Polvilhe açúcar, pimenta-do-reino, sal e azeite",
          "Asse em forno preaquecido a 200ºC até os tomates caramelizarem",
          "Transfira-os para uma tigela e finalize o tempero com vinagre balsâmico."
        ],
        id_video: "efS4wQ-F1PI",
        tempo: "30 minutos",
        porcao: "3",
        por: "Os Chefes Ocasionais",
        img: "tomate",
        tipo: "entrada",
      },
      {
        nome: "Aperitivo de azeitona com salame",
        ingredientes: [
          "Salame italiano",
          "Mussarela em cubos",
          "Azeitonas sem caroço",
          "Azeite",
          "Orégano",
          "Sal",
          "Pimenta-do-reino",
          "Limão",
        ],
        modo_preparo: [
          "Dobre um pedaço de salame e coloque em cima da mussarela. Espete com um palito de madeira e adicione uma azeitona",
          "Repita o processo para fazer a quantidade de aperitivos desejados",
          "Tempere com azeite, orégano, sal, pimenta-do-reino e limão.",
        ],
        id_video: "eZbn1yyx1ck",
        tempo: "20 minutos",
        porcao: "10",
        por: "Bebida Liberada",
        img: "salame",
        tipo: "entrada",
      },
      {
        nome: "Sanduíche de damasco com cream cheese",
        ingredientes: [
          "Damasco seco",
          "Cream cheese",
          "Castanha-de-caju triturada",
        ],
        modo_preparo: [
          "Corte o damasco ao meio, deixando-o ligado por uma ponta",
          "Recheie com cream cheese",
          "Passe o lado da abertura nas castanha",
        ],
        id_video: "oC_j24ewdiM",
        tempo: "20 minutos",
        porcao: "10",
        por: "Luiza Zaidan",
        img: "sanduiche",
        tipo: "entrada",
      },
    ],
    principal: [
      {
        nome: "Panqueca de carne moída",
        ingredientes: [
          "500g de carne moída",
          "Alho picado 4 dentes",
          "Cebola picada 1 unidade",
          "Azeitona verde picada 1/2 xícara (50g)",
          "Molho de tomate 1/2 xícara (120 mL)",
          "Muçarela ralada 120g",
          "Óleo 2 colheres de sopa (26 mL)",
          "Água 1/2 xícara (120 mL)",
          "Sal a gosto",
          "Pimenta do reino a gosto",
          "Orégano a gosto",
          "Salsinha a gosto",
          "Farinha de trigo 2 xícaras (240g)",
          "Leite 2 xícaras (480 mL)",
          "Ovo 2 unidades",
          "Óleo 1 colher de sopa (13 mL)",
          "Sal 1 colher de chá (5g)"
        ],
        modo_preparo: [
          "No liquidificador, bata todos os ingredientes da massa até ficar homogêneo. Deixe descansar por 20 minutos",
          "Enquanto isso prepare o recheio: numa frigideira aqueça o azeite e refogue a cebola e o alho por 1 minuto até murcharem. Junte a carne e refogue até dourar por igual mexendo bem para desmanchar",
          "Acrescente o extrato de tomate e o cubo de caldo de carne KNORR já dissolvido na água. Tampe a panela e deixe cozinhar por 5 minutos mexendo de vez em quando. Retire do fogo, junte a salsa e reserve",
          "Após o tempo de descanso da massa, aqueça uma frigideira antiaderente em fogo médio. Unte com manteiga ou óleo e derrame com uma concha da massa no centro fazendo movimentos circulares para espalhar a massa na frigideira.",
          "Quando a panqueca perder o aspecto de molhada e começar a aparecer bolhas, vire com uma espátula. Aguarde dourar do outro lado e transfira para um prato. Repita o procedimento até acabar a massa.",
          "Recheie os discos de panqueca com o recheio reservado e enrole.",
          "Disponha em um refratário e cubra com o molho de sua preferência.",
        ],
        id_video: "tvgM2v0GkIw",
        tempo: "80 minutos",
        porcao: "3",
        por: "Cook'n Enjoy",
        img: "panqueca",
        tipo: "principal",
      },
      {
        nome: "Camarão na moranga",
        ingredientes: [
          "Abóbora moranga 1 unidade (+ou-4kg)",
          "Requeijão cremoso 150g",
          "Óleo para pincelar",
          "Camarão limpo 1,2 kg",
          "Cebola picada 2 unidades",
          "Alho amassado 6 dentes",
          "Tomate sem sementes picado 5 unidades",
          "Limão 1/2 unidade",
          "Requeijão cremoso 400g",
          "Leite de coco 1 garrafinha (200 mL)",
          "Azeite de oliva 3 colheres de sopa (39 mL)",
          "Sal a gosto",
          "Pimenta do reino a gosto",
          "Salsinha a gosto"
        ],
        modo_preparo: [
          "Retire a tampa e as sementes da moranga.",
          "Lave e enrole-a em papel alumínio e leve ao forno médio (180° C) por 45 minutos.",
          "Em uma panela, aqueça o azeite e refogue o alho e a cebola, junte o camarão e deixe cozinhar por 5 minutos.",
          "Adicione os tomates picados, a pimenta, o sal e o ketchup.",
          "Desligue o fogo e acrescente o creme de leite e o cheiro-verde.",
          "Misture bem e adicione por último o requeijão.",
          "Passe um pouco de requeijão no interior da moranga e despeje o creme de camarão."
        ],
        id_video: "rOujUqCjCiU",
        tempo: "90 minutos",
        porcao: "6",
        por: "Cook'n Enjoy",
        img: "camarao",
        tipo: "principal",
      },
      {
        nome: "Medalhão de filé mignon com risoto de queijo",
        ingredientes: [
          "250g de filé mignon",
          "1 colher de sopa de azeite",
          "1 colher de sopa de manteiga",
          "2 fatias de bacon",
          "sal e pimenta do reino a gosto",
          "150g de arroz arbóreo",
          "2 colheres de sopa de azeite",
          "½ cebola picada em cubinhos",
          "1 cálice de vinho branco",
          "100g de queijo Gruyère ou parmesão ralado",
          "1 colher de manteiga",
          "250ml de caldo de legumes"
        ],
        modo_preparo: [
          "Em uma frigideira preaquecida, coloque o medalhão já temperado com sal rosa do Himalaia Kitano ",
          "Reserva para tostar em ambos os lados e flambe o filé colocando um talo de alecrim.",
          "Deixe grelhar até o ponto desejado.",
          "Quando estiver pronto, retire o alecrim e coloque 15 gramas de manteiga e também coloque o mix de pimentas Kitano Reserva Risoto",
          "Em uma panela, aqueça o azeite e coloque a cebola picada para bronzear.",
          "Despeje o arroz e acrescente o caldo de galinha e o vinho.",
          "Coloque o sal rosa do Himalaia Kitano Reserva, e deixe a chama no mínimo.",
          "Deixe tampado até secar o líquido.",
          "Coloque o risoto para descansar em uma base de mármore bem aberta.",
          "Enquanto prepara a carne, finalize o risoto com mais caldo até chegar no ponto desejado no fogo.",
          "Complete com manteiga e parmesão e mexa para dar brilho já fora do fogão.",
        ],
        id_video: "F2-Va5jPg7Q",
        tempo: "90 minutos",
        porcao: "2",
        por: "SALÔ GASTRÔ",
        img: "risoto",
        tipo: "principal",
      },
      {
        nome: "Lasanha a bolonhesa",
        ingredientes: [
          "Carne moída 500g",
          "Óleo 2 colheres de sopa (26 mL)",
          "Molho de tomate 3 xícaras (720 mL)",
          "Polpa tomate 1/2 xícara (120 mL)",
          "Água 1 xícara (240 mL)",
          "Cebola picada 1 unidade e 1/2",
          "Alho picado 4 dentes",
          "Sal a gosto",
          "Cominho em pó a gosto",
          "Pimenta do reino a gosto",
          "Orégano a gosto"
        ],
        modo_preparo: [
          "Cozinhe a massa de acordo com as instruções da embalagem e coloque em um recipiente com água fria até o momento de montar. Molho Bolonhesa",
          "Em uma panela, aqueça o óleo e refogue a carne. Junte a cebola, a cenoura, o salsão e deixe refogar até murchar.",
          "Acrescente a polpa de tomate e o tablete de MAGGI Caldo, dissolvido em na água quente.",
          "Deixe cozinhar por cerca de 10 minutos, ou até apurar o molho. Reserve. Molho Branco",
          "Em uma panela, derreta a manteiga, junte a farinha de trigo e deixe dourar.",
          "Aos poucos junte o Leite NINHO, mexendo sempre para não formar grumos. Acrescente a noz moscada, o sal, e a pimenta-do-reino.",
          "Quando adquirir consistência cremosa, retire do fogo, acrescente o NESTLÉ Creme de Leite, misture bem e reserve.",
          "Em um recipiente refratário (20 x 30 cm), coloque uma porção de molho bolonhesa; cubra com uma camada de massa, e uma porção de molho branco e coloque o queijo mozarela. Repita as camadas até a borda do recipiente.",
          "Finalize com o queijo parmesão ralado e leve ao forno alto (220°C), preaquecido, por cerca de 20 minutos ou até dourar. Sirva."
        ],
        id_video: "2SUFQ19cQVw",
        tempo: "90 minutos",
        porcao: "12",
        por: "Cook'n Enjoy",
        img: "lasanha",
        tipo: "principal",
      },
      {
        nome: "Fricassê de Frango com Milho",
        ingredientes: [
          "1 colher (sopa) de manteiga",
          "1 peito de frango cozido e desfiado",
          "2 tabletes de MAGGI® Caldo Galinha",
          "meia xícara (chá) de água quente",
          "1 lata de NESTLÉ® Creme de Leite",
          "1 lata de milho-verde escorrida",
          "2 xícaras (chá) de Leite Líquido NINHO® Forti+ Integral",
          "2 colheres (sopa) de amido de milho",
          "1 xícara (chá) de queijo mozarela ralado",
          "1 xícara (chá) de batata palha",
        ],
        modo_preparo: [
          "Em uma panela, aqueça a manteiga e refogue o frango. Acrescente o MAGGI Caldo e a água quente e refogue até que o Caldo esteja dissolvido e não haja excesso de líquido.",
          "Junte o Creme de Leite NESTLÉ, misture bem e transfira o conteúdo para um recipiente refratário médio e reserve em local aquecido.",
          "Em um liquidificador, bata meia lata de milho-verde com o Leite NINHO.",
          "Em uma panela, acrescente o que foi batido no liquidificador, o milho-verde restante e o amido de milho, mexendo bem para não criar grumos. Leve ao fogo baixo, mexendo sempre, até engrossar.",
          "Despeje o creme de milho sobre o frango reservado, salpique a mozarela e leve ao forno médio (180°C), preaquecido, por cerca de 15 minutos ou até dourar. Coloque a batata palha e sirva."
        ],
        id_video: "TXVMPnvVAhM",
        tempo: "45 minutos",
        porcao: "8",
        por: "Receitas Nestlé",
        img: "frango",
        tipo: "principal",
      },
    ],
    sobremesa: [
      {
        nome: "Manjar",
        ingredientes: [
          "1 Leite MOÇA® (lata ou caixinha) 395g",
          "2 e meia medidas (da lata) de Leite Líquido NINHO® Forti+ Integral",
          "1 vidro de leite de coco (200ml)",
          "meia xícara (chá) de amido de milho",
          "1 e meia xícara (chá) de açúcar",
          "1 xícara (chá) de ameixas pretas",
          "1 pedaço de canela em pau",
          "2 cravos-da-índia",
          "2 e meia xícaras (chá) de água",
        ],
        modo_preparo: [
          "Em uma panela, misture bem o Leite MOÇA, o Leite NINHO, o leite de coco e o amido de milho.",
          "Leve ao fogo, mexendo sempre, até obter um creme grosso.",
          "Retire do fogo, despeje em uma forma com furo central (19 cm de diâmetro) molhada ou levemente untada com óleo e leve à geladeira por cerca de 4 horas.",
          "Reserve.",
          "Em uma panela, misture o açúcar, as ameixas, a canela, o cravo e a água.",
          "Leve ao fogo e cozinhe por cerca de 10 minutos após iniciar fervura.",
          "Sirva a calda fria com sobre o manjar reservado.",
        ],
        id_video: "OCdVjnmXhqc",
        tempo: "260 minutos",
        porcao: "10",
        por: "Receitas Nestlé",
        img: "manjar",
        tipo: "sobremesa",
      },
      {
        nome: "Torta de Limão",
        ingredientes: [
          "2 xícaras (chá) de farinha de trigo",
          "4 colheres (sopa) de manteiga",
          "meia lata de NESTLÉ® Creme de Leite",
          "1 colher (chá) de fermento em pó",
          "1 Leite MOÇA® (lata ou caixinha) 395 g",
          "6 colheres (sopa) de suco de limão",
          "meia lata de NESTLÉ® Creme de Leite",
          "1 colher (sopa) de raspas da casca de limão",
          "3 claras",
          "meia xícara (chá) de açúcar",
        ],
        modo_preparo: [
          "Em um recipiente, peneire a farinha de trigo, faça uma cova no centro e coloque a manteiga, o NESTLÉ Creme de Leite e o fermento em pó.",
          "Misture-os com as pontas dos dedos, até que a massa solte completamente das mãos.",
          "Deixe descansar por cerca de 30 minutos na geladeira.",
          "Em uma superfície limpa, polvilhada com farinha de trigo, abra a massa, forre uma forma de fundo removível (24 cm de diâmetro), fure o fundo com um garfo e asse em forno médio-alto (200°C), preaquecido, por cerca de 20 minutos. Reserve.",
          "Em um recipiente, misture bem o Leite MOÇA com o suco de limão. Incorpore o NESTLÉ Creme de Leite e as raspas de limão.",
          "Recheie a massa já assada e leve à geladeira por cerca de 30 minutos, para firmar o recheio. Reserve.",
          "Em uma panela, misture as claras e o açúcar e leve ao fogo baixo, mexendo vigorosamente sem parar, por cerca de 3 minutos, tirando a panela do fogo por alguns instantes a cada minuto, continuando a mexer, para não cozinhar.",
          "Retire do fogo e em uma batedeira, bata por cerca de 5 minutos ou até dobrar de volume.",
          "Desligue a batedeira, retire a torta da geladeira e cubra-a com o merengue. Retorne a torta ao forno por cerca de 10 minutos, para dourar. Sirva gelada.",
        ],
        id_video: "kf2RWtoV4f0&t=1s",
        tempo: "100 minutos",
        porcao: "16",
        por: "Receitas Nestlé",
        img: "tortaLimao",
        tipo: "sobremesa",
      },
      {
        nome: "Bolo de Cenoura com Cobertura de Brigadeiro",
        ingredientes: [
          "3 cenouras médias (250g)",
          "4 ovos",
          "meia xícara (chá) de óleo",
          "2 e meia xícaras (chá) de farinha de trigo",
          "2 xícaras (chá) de açúcar",
          "1 colher (sopa) de fermento em pó",
          "1 Leite MOÇA® (lata ou caixinha) 395g",
          "1 colher (sopa) de manteiga",
          "meia xícara (chá) de Chocolate em Pó NESTLÉ® DOIS FRADES®",
          "meia xícara (chá) de chocolate granulado",
        ],
        modo_preparo: [
          "Em um liquidificador, bata as cenouras, os ovos e o óleo.",
          "Despeje a mistura em um recipiente e misture o açúcar e a farinha de trigo peneirada com o fermento.",
          "Coloque em uma fôrma retangular (20 x 30 cm) untada, e leve ao forno médio (180°C), preaquecido, por 40 minutos.",
          "Enquanto isso, prepare a cobertura de brigadeiro.",
          "Em uma panela coloque o Leite MOÇA, o Chocolate em Pó DOIS FRADES e a manteiga e leve ao fogo baixo, mexendo sempre, até começar a desprender da panela.",
          "Despeje ainda quente sobre o bolo, distribua o chocolate granulado e deixe esfriar.",
        ],
        id_video: "pobqPedHD5w&t=1s",
        tempo: "70 minutos",
        porcao: "20",
        por: "Receitas Nestlé",
        img: "boloCenoura",
        tipo: "sobremesa",
      },
      {
        nome: "Mousse de Chocolate",
        ingredientes: [
          "1 lata de NESTLÉ® Creme de Leite",
          "200 g de Chocolate NESTLÉ® CLASSIC® Meio Amargo picado",
          "3 claras",
          "3 colheres (sopa) de açúcar",
        ],
        modo_preparo: [
          "Em uma panela em banho-maria, aqueça o NESTLÉ Creme de Leite.",
          "Junte o Chocolate NESTLÉ CLASSIC e mexa até que fique uma mistura homogênea. Reserve.",
          "Em uma panela, misture as claras e o açúcar e leve ao fogo baixo, mexendo vigorosamente sem parar, por cerca de 3 minutos, tirando a panela do fogo por alguns instantes a cada minuto, continuando a mexer, para não cozinhar.",
          "Transfira para uma batedeira e bata por 5 minutos ou até dobrar de volume.",
          "Misture levemente ao creme de Chocolate.",
          "Coloque em taças e leve à geladeira por cerca de 3 horas.",
          "Decore com cerejas, chantilly ou raspas de chocolate.",
        ],
        id_video: "rG1osb8STH0&t=2s",
        tempo: "200 minutos",
        porcao: "6",
        por: "Receitas Nestlé",
        img: "mousse",
        tipo: "sobremesa",
      },
      {
        nome: "Pudim de Leite Moça",
        ingredientes: [
          "1 xícara (chá) de açúcar",
          "meia xícara (chá) de água quente",
          "1 Leite MOÇA® (lata ou caixinha) 395 g",
          "2 medidas (da lata) de Leite Líquido NINHO® Forti+ Integral (790 ml)",
          "3 ovos",
        ],
        modo_preparo: [
          "Em uma panela de fundo largo, derreta o açúcar até ficar dourado.",
          "Junte a água quente e mexa com uma colher.",
          "Deixe ferver até dissolver os torrões de açúcar e a calda engrossar.",
          "Forre com a calda uma forma com furo central (19 cm de diâmetro) e reserve.",
          "Em um liquidificador, bata todos os ingredientes do pudim e despeje na forma reservada.",
          "Cubra com papel-alumínio e leve ao forno médio (180°C), em banho-maria, por cerca de 1 hora e 30 minutos.",
          "Depois de frio, leve para gelar por cerca de 6 horas.",
          "Desenforme e sirva a seguir.",
          "É essencial que o pudim seja preparado em banho-maria para que asse de forma lenta e controlada, para atingir a textura ideal.",
          "Para que o seu pudim não forme furinhos, verifique se a temperatura do forno está regulada conforme indicação da receita. Leve a forma ao forno na grade superior, longe da chama.",
        ],
        id_video: "XAU1wx2PPSE&t=168s",
        tempo: "480 minutos",
        porcao: "16",
        por: "Receitas Nestlé",
        img: "pudim",
        tipo: "sobremesa",
      },
    ],
    vegano: [
      {
        nome: "Bolo de Abacaxi Caramelizado",
        ingredientes: [
          "1 abacaxi",
          "2 xícaras farinha de trigo",
          "1½ xícaras açúcar",
          "1 colher (chá) fermento em pó",
          "1 colher (chá) bicarbonato de sódio",
          "1 colher (sopa) vinagre",
          "200 ml leite de coco",
          "80 ml óleo",
        ],
        modo_preparo: [
          "Tire a casca do abacaxi e corte metade dele em rodelas, que vamos usar para cobrir o bolo mais tarde.",
          "Em um liquidificador, coloque a outra metade do abacaxi (cortado em pedaços) e o leite de coco e bata. Adicione o resto do açúcar, o óleo e bata novamente até virar um creme.",
          "Em um recipiente grande, peneire a farinha de trigo, adicione o bicarbonato de sódio e misture com a ajuda de um fouet. Vá adicionando o creme de abacaxi aos poucos e batendo, incorporando à massa.",
          "Por último, adicione o vinagre e o fermento e mexa com cuidado.",
          "Para fazer o caramelo, coloque cerca de 7 colheres (sopa) de açúcar na forma e derreta levando ao forno ou na boca do fogão.",
          "Unte toda a superfície da forma com o caramelo e ajeite as rodelas de abacaxi no fundo para formar uma cama, e despeje a massa por cima.",
          "Leve ao forno pré aquecido a 200 graus por cerca de 50 minutos. Prontinho!",
        ],
        id_video: "VRYGXEUZ6Vs",
        tempo: "70 minutos",
        porcao: "4",
        por: "Vegana Pratica",
        img: "boloAbacaxi",
        tipo: "vegano",
      },
      {
        nome: "Torta de Morango Vegana",
        ingredientes: [
          "1½ xícara farinha de trigo",
          "4 colheres (sopa) açúcar cristal",
          "⅓ xícara óleo",
          "⅓ xícara água",
          "3 xícaras leite vegetal",
          "⅔ xícara açúcar cristal",
          "3 colheres (sopa) amido de milho",
          "1 colher (chá) essência de baunilha",
          "2 bandejas morango",
          "½ xícara açúcar",
          "⅓ xícara água",
        ],
        modo_preparo: [
          "Em um recipiente grande, despeje a farinha de trigo, o açúcar, a água e o óleo, e mexa bem com as mãos, até formar uma bola com a massa.",
          "Pré aqueça o forno a 200 graus. Unte uma forma com óleo e abra a massa, ajustando nos cantos.",
          "Espete a massa com um garfo e leve ao forno até ficar crocante, por cerca de 40 minutos.",
          "Em uma panela, adicione o leite vegetal e o açúcar até chegar em uma textura de leite condensado.",
          "Dilua o amido de milho em um copo de água e adicione à mistura, e também a essência de baunilha, mexendo por alguns minutos, até engrossar.",
          "Quando estiver pronto, despejar na forma com a massa já assada.",
          "Pique os morangos ao meio e coloque por cima do creme branco na torta.",
          "Em uma panela, adicione a água e o açúcar até ferver a água. Desligue, espere esfriar e despeje por cima dos morangos.",
          "Leve à geladeira por 2 horas e pode se deliciar. Prontinho!",
        ],
        id_video: "xMYWqMLFv6s&t=301s",
        tempo: "70 minutos",
        porcao: "4",
        por: "Vegana Pratica",
        img: "tortaMorango",
        tipo: "vegano",
      },
      {
        nome: "Bolinho de Arroz Vegano",
        ingredientes: [
          "2 xícaras arroz cozido",
          "1 cenoura",
          "½ copo água",
          "4 colheres (sopa) chia ou linhaça",
          "1 colher (chá) fermento em pó",
          "½ cebola",
          "½ limão (sumo)",
          "1 dente alho",
          "1 colher (sopa) páprica",
          "1 colher (chá) cominho",
          "3 colheres (sopa) azeite de oliva",
          "sal, salsinha",
          "farinha de milho (para empanar)",
        ],
        modo_preparo: [
          "Aqueça um fio de óleo em uma frigideira e refogue a cebola e o alho picados. Adicione páprica e cominho e mexa bem.",
          "Jogue a cenoura ralada, finalize com sal e mexa. Desligue o fogo e transfira para um recipiente.",
          "Coloque o forno para pré-aquecer a 200 graus.",
          "Em meio copo, coloque 3 colheres de chia e deixe repousar (esse será o nosso substituto do ovo).",
          "Enquanto repousa, pique os temperos da sua preferência (como salsinha, cebolinha, orégano…).",
          "No recipiente com o refogado, misture o arroz cozido, o limão espremido, os temperos e a chia. Adicione o fermento e mexa com cuidado.",
          "Despeje farinha de milho em um prato, faça bolinhas com a massa e empane na farinha. Pincele os bolinhos com azeite e leve ao forno por 40 minutos, virando na metade do tempo. Prontinho!",
        ],
        id_video: "IxLDshWYteA",
        tempo: "60 minutos",
        porcao: "5 pessoas",
        por: "Vegana Pratica",
        img: "bolinhoArroz",
        tipo: "vegano",
      },
      {
        nome: "Croquete de Mandioca Vegano",
        ingredientes: [
          "500 gramas mandioca",
          "1½ xícara farinha de trigo",
          "½ xícara farinha de rosca",
          "½ unidade cebola",
          "1 colher (chá) fermento em pó",
          "sal e azeite",
        ],
        modo_preparo: [
          "Cozinhe a mandioca na água até ficar macia e retire os 'fios' mais duros. Leve ao processador ou liquidificador e bata bem.",
          "Adicione a farinha, sal, cebola picada, suco de meio limão, salsinha e açafrão, e mexer com uma espátula para incorporar tudo.",
          "Finalize com pimenta e o fermento em pó, mexendo delicadamente. Leve ao freezer p0r 10 minutos.",
          "Em um prato, coloque a farinha da sua preferência e tempere com sal.",
          "Unte as mãos com um pouco de óleo, forme os croquetes e passe na farinha, empanando-os.",
          "Leve os croquetes a uma forma e besunte com azeite de oliva.",
          "Pré aqueça o forno a 200 graus e leve os croquetes para assar por cerca de 30 minutos ou até dourarem. Prontinho!",
        ],
        id_video: "C5OBHCHAA1Q",
        tempo: "60 minutos",
        porcao: "3 pessoas",
        por: "Vegana Pratica",
        img: "croqueteMandioca",
        tipo: "vegano",
      },
      {
        nome: "Geleia de Manga com Pimenta",
        ingredientes: [
          "3 mangas",
          "2 pimentas dedo-de-moça",
          "1 dente alho",
          "2 cravos",
          "⅔ xícara açúcar",
          "½ limão",
          "1 colher (sopa) óleo",
          "1 pitada canela em pó",
        ],
        modo_preparo: [
          "Comece descascando as mangas e picando em cubos.",
          "Faça o mesmo com a pimenta dedo-de-moça, retirando as sementes se não quiser muito picante (lembrando de lavar muito bem as mãos depois de cortar a pimenta!).",
          "Pique o alho e leve a uma panela com óleo para refogar. Adicione as pimentas picadas e os cravos. Refogue bem e adicione as mangas. Vá mexendo até elas amolecerem. Adicione o açúcar.",
          "Encha meio copo com água e esprema um limão, misturando os dois, e leve à panela. Adicione a pitada de canela, mexendo sem parar até atingir a consistência desejada.",
          "Transfira a geleia para um pote de vidro. Prontinho!",
        ],
        id_video: "LDlsgfsbTS0&t=1s",
        tempo: "60 minutos",
        porcao: "8",
        por: "Vegana Pratica",
        img: "geleiaManga",
        tipo: "vegano",
      },
    ],
  };
  